<?php
declare(strict_types=1);

use App\P005_SmallestMultiple\SmallestMultiple;
use PHPUnit\Framework\TestCase;

class SmallestMultipleTest extends TestCase
{
    /** @var SmallestMultiple */
    private $smallestMultiple;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->smallestMultiple = new SmallestMultiple();
    }

    public function testCalculate(int $testNumber, int $expectedResult): void
    {
        $this->assertEquals($expectedResult, $this->smallestMultiple->calculate($testNumber));
    }

    public function cases(): array
    {
        return [
            [5, 60],
            [7, 420],
            [10, 2520],
            [13, 360360],
            [20, 232792560],
        ];
    }
}
